/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AssetObjectPageObjectPage journey");

        opaTest("Navigate to AssetObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheAssetListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAssetListGenerated.onTable().iCheckRows();
            When.onTheAssetListGenerated.onTable().iPressRow(0);

            Then.onTheAssetObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the GeneratedFacet1 section of the Object Page", function (_Given, _When, Then) {
            Then.onTheAssetObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MasterFixedAsset" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FixedAsset" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetRowID" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetNumberDisplay" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetTag" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreationDate" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ItemCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetDescription" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GoodsReceiptDocument" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DisbursementVoucher" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SerialNumber" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GroupCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GroupName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetClass" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetClassName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AcquisitionDate" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CategoryCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CategoryName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CostCenter" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CostCenterName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OwnerCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OwnerName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BranchCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BranchName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProfitCenter" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProfitCenterName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Segment" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SegmentName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetLocation" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "LocationName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Room" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SublocationCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SublocationName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DepartmentCode" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DepartmentName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCodeCurrency" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AcquisitionCost" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CapitalizationDate" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PlannedUsefulLifeInPeriods" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PlannedUsefulLifeInYears" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "UsefulLifeDisplay" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetIsRetired" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PlannedRetirementDate" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AssetRealDepreciationArea" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PurchaseOrder" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PurchaseOrderItem" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCodeName" });
            Then.onTheAssetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreatedByUser" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});