/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AssetListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheAssetListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheAssetListGenerated.onFilterBar().iCheckFilterField({ property: "CompanyCode" });
            Then.onTheAssetListGenerated.onFilterBar().iCheckFilterField({ property: "CreationDate" });
            Then.onTheAssetListGenerated.onFilterBar().iCheckFilterField({ property: "AssetClass" });
            Then.onTheAssetListGenerated.onFilterBar().iCheckFilterField({ property: "MasterFixedAsset" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheAssetListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheAssetListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheAssetListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheAssetListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheAssetListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheAssetListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"AssetRowID":{"header":"#"},"MasterFixedAsset":{"header":"Asset No."},"AssetTag":{"header":"Asset Tag"},"ItemCode":{"header":"Item Code"},"AssetDescription":{"header":"Asset Description"},"GoodsReceiptDocument":{"header":"Asset Details"},"SerialNumber":{"header":"Serial No."},"GroupCode":{"header":"Group Code"},"GroupName":{"header":"Group Name"},"AssetClass":{"header":"Class Code"},"AssetClassName":{"header":"Class Name"},"CategoryCode":{"header":"Category Code"},"CategoryName":{"header":"Category Name"},"CostCenter":{"header":"Cost Center Code"},"OwnerCode":{"header":"Owner Code"},"CostCenterName":{"header":"Cost Center Name"},"OwnerName":{"header":"Owner Name"},"BranchCode":{"header":"Branch Code"},"BranchName":{"header":"Branch Name"},"AssetLocation":{"header":"Location Code"},"LocationName":{"header":"Location Name"},"SublocationCode":{"header":"Sublocation Code"},"SublocationName":{"header":"Sublocation Name"},"DepartmentCode":{"header":"Department Code"},"DepartmentName":{"header":"Department Name"},"AcquisitionCost":{"header":"Acquisition Cost"},"AcquisitionDate":{"header":"Acquisition Date"},"UsefulLifeDisplay":{"header":"Useful Life"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheAssetListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAssetListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheAssetListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheAssetObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});